// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Quarterly_Sales_App.Data;

#nullable disable

namespace Quarterly_Sales_App.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Quarterly_Sales_App.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DOB")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfHiring")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("ManagerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DOB = new DateTime(1996, 12, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfHiring = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Grace",
                            LastName = "Hopper",
                            ManagerName = "Tim Cook"
                        },
                        new
                        {
                            Id = 2,
                            DOB = new DateTime(1998, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfHiring = new DateTime(2022, 9, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Tim",
                            LastName = "Cook",
                            ManagerName = ""
                        },
                        new
                        {
                            Id = 3,
                            DOB = new DateTime(1999, 11, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfHiring = new DateTime(2021, 8, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Jhon",
                            LastName = "Rock",
                            ManagerName = "Tim Cook"
                        });
                });

            modelBuilder.Entity("Quarterly_Sales_App.Models.Sales", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<long>("Amount")
                        .HasColumnType("bigint");

                    b.Property<string>("EmployeeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quarter")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Sales");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 100000L,
                            EmployeeName = "Tim Cook",
                            Quarter = 1,
                            Year = 2021
                        },
                        new
                        {
                            Id = 2,
                            Amount = 100000L,
                            EmployeeName = "Tim Cook",
                            Quarter = 3,
                            Year = 2022
                        },
                        new
                        {
                            Id = 3,
                            Amount = 100000L,
                            EmployeeName = "Tim Cook",
                            Quarter = 4,
                            Year = 2019
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
